import pandas as pd
import numpy as np
 

mat_log = pd.read_csv('cloud_computing_log.csv', index_col=0, sep=';')
vec_prices = pd.read_csv('cloud_computing_prices.csv', index_col=0, sep=';',header=None) #first row in file is data not a header

print(mat_log)
print(vec_prices)

vec_cost = np.dot( mat_log, vec_prices)
vec_cost


x = np.linspace(-5,5,100)
print(type(x))

y_1 = 2 * x 
y_2 = (x + 3)/2

import matplotlib.pyplot as plt

fig,ax = plt.subplots(nrows=1)
ax.plot(x,y_1,label='Line 1')
ax.plot(x,y_2,label='Line 2')
ax.set(xlabel='X',ylabel='Y')
ax.legend()


vec_x =  [1,0]
vec_y =  [0,1]
mat_transform =np.array([[1,1],[-1,1]])
mat_transform


vec_x_transformed = np.dot(mat_transform,vec_x)
vec_y_transformed = np.dot(mat_transform,vec_y)
print(vec_x_transformed)
print(vec_y_transformed)



mat_identity = np.array([[1,0],[0,1]])
print(np.dot(mat_identity, vec_x))
print(np.dot(mat_identity, vec_y))


# Create Matrices 
np.eye(6)

A = np.array([[1,2,3,4],[5,6,7,8]])
B = np.array([[1,2],[3,4],[5,6],[7,8]])
print(np.dot(A,B))
print(np.dot(B,A))



C = np.array([[1,2],
              [3,4]])
D = np.array([[5,6],
              [7,8]])
print(np.dot(C,D))
print(np.dot(D,C))




print(np.dot(C,D))
print(np.dot(D,C))
print(C*D)
print(D*C)


vec_1 = np.array([3 ,2, 3, 2] )
vec_2 = np.array([4, 1])

print(A )
print('**********')
print(B)
print('**********')
print(C)
print('**********')
print(A+vec_1)
print('********** abajo')
print(np.dot(A,vec_1))
print('**********')
print(B+vec_2)
print('**********')
print(C+vec_2)


# Remember:

# Multiplication of matrix and vector by numpy.dot(my_matrix, my_vector).
# The term linear equation describes the multiplication of a matrix by a vector.
# Each vector can be generated by a sum of the base vectors.